<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.2" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>f84ec54c-5dd0-4ea9-95ac-78e100d77bd8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.5.2" />
    <PackageReference Include="Aspire.Hosting.Azure.AppContainers" Version="9.5.2" />
    <PackageReference Include="Aspire.Hosting.Azure.ApplicationInsights" Version="9.5.2" />
    <PackageReference Include="Aspire.Hosting.Azure.KeyVault" Version="9.5.2" />
    <PackageReference Include="Aspire.Hosting.Azure.ServiceBus" Version="9.5.2" />
    <PackageReference Include="Aspire.Hosting.Azure.Storage" Version="9.5.2" />
    <PackageReference Include="Aspire.Hosting.Keycloak" Version="9.5.2-preview.1.25522.3" />
    <PackageReference Include="Aspire.Hosting.Azure.PostgreSQL" Version="9.5.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameStore.Api\GameStore.Api.csproj" />
    <ProjectReference Include="..\GameStore.Worker\GameStore.Worker.csproj" />
    <ProjectReference Include="..\StripeCLI.Hosting\StripeCLI.Hosting.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
